# Generated by Django 5.0 on 2023-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todolist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=False,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo", models.TextField()),
            ],
        ),
    ]
